config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  devise_for :users

  resources :lists do
  	resources :tasks do
  		member do
  			patch :complete
  		end
  	end
  end
 
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	belongs_to :user
	has_many :tasks, :dependent => :delete_all

	validates_presence_of :title
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :list

	validates_presence_of :title
	validates :title, length: { :maximum => 50 }

	def done?
		is_done == true
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :lists, :dependent => :delete_all

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    
    if user_signed_in?
      @lists = List.where(:user_id => current_user.id).order("created_at DESC")
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    respond_to do |format|
      @list = current_user.lists.build(list_params)

      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:complete, :destroy]
  before_action :set_list, only: [:create, :complete, :destroy]

	def create
		respond_to do |format|
			@task = @list.tasks.create(task_params)
			if @task.save
				ListChannel.broadcast(@task)
				format.html { redirect_to @list, notice: 'Task added' }
			else
				format.html { redirect_to @list, notice: 'Enter task name' }
			end
		end
	end

	def complete
		@task.update_attribute(:is_done, true)
		ListChannel.broadcast(@task)
		redirect_to @list
	end

	def destroy
    @task.destroy
		ListChannel.broadcast(@task)
    respond_to do |format|
      format.html { redirect_to @list, notice: 'Task deleted' }
    end
	end

	private
		def set_task
      @task = Task.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

		def task_params
			params.require(:task).permit(:title, :is_done, :list_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_starting_page.html.erb
<div class="jumbotron">
	<h1>Try your custom Checklists</h1>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= params[:controller].parameterize %>_controller">
  	<nav class="navbar navbar-inverse">
  		<div class="container-fluid">
    		<div class="navbar-header">
    			<%= link_to "My Lists", root_path, class: "navbar-brand" %>
    		</div>

				<ul class="nav navbar-nav">
					<li><%= link_to "Sign Up", new_user_registration_path %></li>

					<% if current_user.present? %>
						<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%= link_to "Log In", new_user_session_path %></li>
					<% end %>
				</ul>

				<% if user_signed_in? %>
					<%= link_to "New List", new_list_path, class: "navbar-text navbar-link navbar-right" %>
				<% end %>
    	</div>

      <p class="notice"><%= notice %></p>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <div class="field">
    <%= f.input :title, required: true, autofocus: true%>
  </div>

  <div class="actions">
    <p><%= f.submit %></p>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="col-md-6 col-md-offset-3 jumbotron">
	<h2><%= @list.title %></h2>

	<%= render 'form', list: @list %>

	<%= link_to 'Show list', @list, class: "btn btn-primary" %>
	<%= link_to 'Back', lists_path, class: "btn btn-primary" %>
</div>

app/views/lists/index.html.erb
<% if user_signed_in? %>
  <div class="col-md-6 col-md-offset-3 jumbotron">
  	<div class="col-md-12">
  		<h1>My lists</h1>
  
	  	<% @lists.each do |list| %>
				<div class="row item">
	    		<h2><%= link_to list.title, list %></h2>
	    	</div>
	  	<% end %>
  	</div>
  </div>
<% else %>
  <%= render 'layouts/starting_page' %>
<% end %>

app/views/lists/new.html.erb
<div class="col-md-6 col-md-offset-3 jumbotron">
	<h1>New List</h1>

	<%= render 'form', list: @list %>

	<%= link_to 'Back', lists_path, class: "btn btn-primary" %>
</div>

app/views/lists/show.html.erb
<div class="col-md-6 col-md-offset-3 jumbotron">
  <h2><%= @list.title %></h2>

  <% if user_signed_in? and current_user.id == @list.user_id %>
    <p><%= "Link to your list: " + request.original_url %></p>
    
    <div class="container">
      <ol>
        <%= render @list.tasks %>

        <%= render 'tasks/new', list: @list %>
      </ol>

      <%= link_to 'Change list title', edit_list_path(@list), class: "btn btn-primary" %>
      <%= link_to 'Delete list', @list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      <%= link_to 'Back', lists_path, class: "btn btn-primary" %>
    </div>
  <% else %>
    <ol>
      <% @list.tasks.each do |task| %>
        <%= render 'tasks/task2', task: task %>
      <% end %>
    </ol>
  <% end %>
</div>

app/views/tasks/_new.html.erb
<%= form_for([@list, @list.tasks.build], remote: true) do |task| %>
  <div class="field">
    <%= task.text_field :title %>
  </div>

  <div class="actions">
  	<p><%= task.submit("Add a Task") %></p>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% if task.done? %>
  <div class="row item">

    <div class="col-md-8">
      <li><strike><%= task.title %></strike></li>
    </div>

    <div class="col-md-2">
      <p><%= link_to complete_list_task_path(task.list, task), method: :patch do %></p>
        <i class="fa fa-lg fa-check"></i>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to list_task_path(task.list, task), method: :delete, data: { confirm: 'Are you sure?' } do %></p>
        <i class="fa fa-lg fa-trash"></i>
      <% end %>
    </div>

  </div>
<% else %>
  <div class="row item">

    <div class="col-md-8">
      <li><%= task.title %></li>
    </div>

    <div class="col-md-2">
      <p><%= link_to complete_list_task_path(task.list, task), method: :patch do %></p>
        <i class="fa fa-lg fa-check"></i>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to list_task_path(task.list, task), method: :delete, data: { confirm: 'Are you sure?' } do %></p>
        <i class="fa fa-lg fa-trash"></i>
      <% end %>
    </div>

  </div>
<% end %>

app/views/tasks/_task2.html.erb
<% if task.done? %>
  <div class="row item">
    <div class="col-md-8">
      <li><strike><%= task.title %></strike></li>
    </div>
  </div>

<% else %>

  <div class="row item">
    <div class="col-md-8">
      <li><%= task.title %></li>
    </div>
  </div>
<% end %>